on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Release and Debug with Gradle
        run: |
          ./gradlew :module:magisk
          ./gradlew :module:magiskDebug

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          retention-days: 90
          name: Zygisk-LocationReportEnabler
          path: module/build/outputs/zip/
      
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            module/build/outputs/zip/zygisk-LocationReportEnabler.zip
            module/build/outputs/zip/zygisk-LocationReportEnabler-debug.zip
